default_stages: [commit, push]



default_language_version:
  python: python3.12.1

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0  # Version du hook
  hooks:
    - id: trailing-whitespace      # Supprime les espaces en fin de ligne
    - id: end-of-file-fixer       # Assure qu'il y a une nouvelle ligne à la fin des fichiers
    - id: check-yaml              # Vérifie la syntaxe des fichiers YAML
    - id: check-added-large-files # Empêche l'ajout de gros fichiers
    - id: debug-statements

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
    - id: flake8



- repo: https://github.com/PyCQA/pylint
  rev: v3.3.8
  hooks:
    - id: pylint
